## Operations of Python Lists

In [1]:
import numpy as np
print("np version:\t" + np.__version__)

np version:	1.26.1


In [2]:
p = [1,2,3,4,5,6]

In [4]:
print(type(p))
print(p)

<class 'list'>
[1, 2, 3, 4, 5, 6]


In [5]:
print(p*3)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [12]:
np_arr = np.array(p)
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [13]:
print(np_arr*3)

[ 3  6  9 12 15 18]


## Functions

In [8]:
x = np.arange(15)

In [9]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
y = x**2 + 5

In [11]:
print(y)

[  5   6   9  14  21  30  41  54  69  86 105 126 149 174 201]


In [14]:
def f(x):
    return -4 * x**3 + 2*x**2 + 65

y = f(x)
print(y)

## Cool vector stuff

In [20]:
x = np.arange(12, dtype=float).reshape(4,3)
print(x)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [23]:
y = np.array([-4,6,3],dtype=float)
print(y)

[-4.  6.  3.]


In [24]:
print(x+y)

[[-4.  7.  5.]
 [-1. 10.  8.]
 [ 2. 13. 11.]
 [ 5. 16. 14.]]


In [25]:
print(x*y)

[[ -0.   6.   6.]
 [-12.  24.  15.]
 [-24.  42.  24.]
 [-36.  60.  33.]]


In [31]:
z = np.arange(12,dtype=float).reshape(3,4)

## Linear Algebra

### Dot Product

In [26]:
import numpy.matlib

In [33]:
print(np.dot(x,z))

[[ 20.  23.  26.  29.]
 [ 56.  68.  80.  92.]
 [ 92. 113. 134. 155.]
 [128. 158. 188. 218.]]


In [34]:
print(np.vdot(x,z))

506.0


### Statistical Functions

In [35]:
np.amax(x[0])

2.0

In [37]:
for i in range(len(x)):
    print(np.amax(x[i]))

2.0
5.0
8.0
11.0
